#!/usr/bin/env bash

# Set up Git Credential Manager
cd ~/Downloads
wget https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.1.2/gcm-linux_amd64.2.1.2.deb
sudo dpkg -i gcm-linux_amd64.*
git-credential-manager configure
git config --global credential.credentialStore secretservice

