#!/bin/sh

# A dmenu wrapper script for system functions.
export WM="i3"
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

wmpid(){ # This function is needed if there are multiple instances of the window manager.
	tree="$(pstree -ps $$)"
	tree="${tree#*$WM(}"
	echo "${tree%%)*}"
}

case "$(printf "🔒 lock\n🚪 leave $WM\n♻️ renew $WM\n🐻 hibernate\n🔃 reboot\n🖥️shutdown\n💤 sleep\n📺 display off" | dmenu -i -p 'Action: ')" in
	'🔒 lock') i3lock; sleep 2; $ctl suspend -i ;;
	"🚪 leave $WM") i3-msg exit ;;
	"♻️ renew $WM") kill -HUP "$(wmpid)" ;;
	'🐻 hibernate') $ctl hibernate -i ;;
	'💤 sleep') $ctl suspend -i ;;
	'🔃 reboot') $ctl reboot -i ;;
	'🖥️shutdown') $ctl poweroff -i ;;
	'📺 display off') xset dpms force off ;;
	*) exit 1 ;;
esac

